import { CATEGORIES, MATERIALS } from "../constants";
import type { Product, ProductCategory, ProductMaterial } from "../types";

export const PRODUCTS: Product[] = [
  {
    id: "blusa-trama-suave",
    name: "Blusa Trama Suave",
    price: 480,
    category: "Vestuário Autoral",
    material: "Algodão Orgânico",
    colorTones: ["Terracota", "Cru"],
    productionMode: "pronta-entrega",
    badge: "Lançamento",
    fiberDescription: "100% Algodão Cru e Terracota",
  },
  {
    id: "cardigan-aurora",
    name: "Cardigan Aurora",
    price: 720,
    category: "Vestuário Autoral",
    material: "Lã Merino Natural",
    colorTones: ["Sálvia"],
    productionMode: "sob-demanda",
    badge: "Em Demanda",
    fiberDescription: "100% Lã Merino Rústica",
  },
  {
    id: "vestido-flora-botanica",
    name: "Vestido Flora Botânica",
    price: 890,
    category: "Vestuário Autoral",
    material: "Linho Puro Brasileiro",
    colorTones: ["Cru"],
    productionMode: "sob-demanda",
    badge: "Edição Limitada",
    fiberDescription: "100% Linho Brasileiro Rústico",
  },
  {
    id: "bolsa-terracota-media",
    name: "Bolsa Terracota Média",
    price: 390,
    category: "Bolsas & Sacolas",
    material: "Algodão Orgânico",
    colorTones: ["Terracota", "Marrom"],
    productionMode: "pronta-entrega",
    badge: "Pronta Entrega",
    fiberDescription: "Algodão Estruturado e Couro Vegano",
  },
  {
    id: "chapeu-solsticio",
    name: "Chapéu Solstício",
    price: 240,
    category: "Acessórios de Cabeça",
    material: "Linho Puro Brasileiro",
    colorTones: ["Sálvia"],
    productionMode: "pronta-entrega",
    fiberDescription: "Fibras Naturais e Ráfia",
  },
  {
    id: "sueter-terra-organica",
    name: "Suéter Terra Orgânica",
    price: 640,
    category: "Vestuário Autoral",
    material: "Lã Merino Natural",
    colorTones: ["Terracota", "Marrom"],
    productionMode: "sob-demanda",
    badge: "Em Demanda",
    fiberDescription: "Lã Merino e Ráfia Rústica",
  },
  {
    id: "top-cropped-vento",
    name: "Top Cropped Vento",
    price: 320,
    category: "Vestuário Autoral",
    material: "Algodão Orgânico",
    colorTones: ["Cru"],
    productionMode: "pronta-entrega",
    fiberDescription: "100% Algodão Penteado",
  },
  {
    id: "manta-raizes",
    name: "Manta Raízes",
    price: 650,
    category: "Casa & Tapeçaria",
    material: "Lã Merino Natural",
    colorTones: ["Marrom", "Terracota"],
    productionMode: "sob-demanda",
    badge: "Edição Limitada",
    fiberDescription: "Lã Merino e Linho Trançado",
  },
  {
    id: "bolsa-praiana-cru",
    name: "Bolsa Praiana Cru",
    price: 310,
    category: "Bolsas & Sacolas",
    material: "Algodão Orgânico",
    colorTones: ["Cru"],
    productionMode: "pronta-entrega",
    fiberDescription: "Algodão Cru Trançado à Mão",
  },
  {
    id: "colete-outono",
    name: "Colete Outono",
    price: 580,
    category: "Vestuário Autoral",
    material: "Lã Merino Natural",
    colorTones: ["Marrom"],
    productionMode: "sob-demanda",
    fiberDescription: "Lã Merino Encorpada",
  },
  {
    id: "turbante-aurora",
    name: "Turbante Aurora",
    price: 180,
    category: "Acessórios de Cabeça",
    material: "Algodão Orgânico",
    colorTones: ["Terracota"],
    productionMode: "pronta-entrega",
    badge: "Pronta Entrega",
    fiberDescription: "Algodão Orgânico Macio",
  },
  {
    id: "saida-de-praia-vento-leve",
    name: "Saída de Praia Vento Leve",
    price: 460,
    category: "Vestuário Autoral",
    material: "Linho Puro Brasileiro",
    colorTones: ["Cru", "Sálvia"],
    productionMode: "pronta-entrega",
    fiberDescription: "Linho Brasileiro Leve",
  },
  {
    id: "bolsa-tapecaria-mineral",
    name: "Bolsa Tapeçaria Mineral",
    price: 520,
    category: "Bolsas & Sacolas",
    material: "Seda Rústica Vegetal",
    colorTones: ["Sálvia", "Marrom"],
    productionMode: "sob-demanda",
    badge: "Edição Limitada",
    fiberDescription: "Seda Vegetal e Fibra de Bananeira",
  },
  {
    id: "almofada-botanica",
    name: "Almofada Botânica",
    price: 260,
    category: "Casa & Tapeçaria",
    material: "Algodão Orgânico",
    colorTones: ["Sálvia", "Cru"],
    productionMode: "pronta-entrega",
    fiberDescription: "Algodão Cru Trançado",
  },
  {
    id: "blusa-ondas-suaves",
    name: "Blusa Ondas Suaves",
    price: 610,
    category: "Vestuário Autoral",
    material: "Seda Rústica Vegetal",
    colorTones: ["Cru"],
    productionMode: "sob-demanda",
    badge: "Lançamento",
    fiberDescription: "Seda Vegetal Rústica",
  },
  {
    id: "boina-terra",
    name: "Boina Terra",
    price: 210,
    category: "Acessórios de Cabeça",
    material: "Lã Merino Natural",
    colorTones: ["Marrom"],
    productionMode: "pronta-entrega",
    fiberDescription: "Lã Merino Encorpada",
  },
  {
    id: "cropped-trama-aberta",
    name: "Cropped Trama Aberta",
    price: 350,
    category: "Vestuário Autoral",
    material: "Algodão Orgânico",
    colorTones: ["Terracota", "Cru"],
    productionMode: "pronta-entrega",
    fiberDescription: "Algodão Orgânico Trançado",
  },
  {
    id: "bolsa-tote-raiz",
    name: "Bolsa Tote Raiz",
    price: 430,
    category: "Bolsas & Sacolas",
    material: "Linho Puro Brasileiro",
    colorTones: ["Marrom"],
    productionMode: "sob-demanda",
    badge: "Em Demanda",
    fiberDescription: "Linho Brasileiro Encorpado",
  },
  {
    id: "kimono-aurora-dourada",
    name: "Kimono Aurora Dourada",
    price: 890,
    category: "Vestuário Autoral",
    material: "Seda Rústica Vegetal",
    colorTones: ["Terracota", "Sálvia"],
    productionMode: "sob-demanda",
    badge: "Edição Limitada",
    fiberDescription: "Seda Vegetal e Algodão",
  },
  {
    id: "tapete-raizes-redondo",
    name: "Tapete Raízes Redondo",
    price: 470,
    category: "Casa & Tapeçaria",
    material: "Algodão Orgânico",
    colorTones: ["Marrom", "Cru"],
    productionMode: "sob-demanda",
    fiberDescription: "Algodão Trançado Grosso",
  },
  {
    id: "faixa-de-cabelo-salvia",
    name: "Faixa de Cabelo Sálvia",
    price: 190,
    category: "Acessórios de Cabeça",
    material: "Algodão Orgânico",
    colorTones: ["Sálvia"],
    productionMode: "pronta-entrega",
    badge: "Pronta Entrega",
    fiberDescription: "Algodão Orgânico Macio",
  },
  {
    id: "bolero-trama-fina",
    name: "Bolero Trama Fina",
    price: 390,
    category: "Vestuário Autoral",
    material: "Lã Merino Natural",
    colorTones: ["Cru"],
    productionMode: "pronta-entrega",
    fiberDescription: "Lã Merino Fina",
  },
  {
    id: "cesto-organizador-trancado",
    name: "Cesto Organizador Trançado",
    price: 280,
    category: "Casa & Tapeçaria",
    material: "Linho Puro Brasileiro",
    colorTones: ["Marrom", "Terracota"],
    productionMode: "pronta-entrega",
    fiberDescription: "Linho Brasileiro Trançado",
  },
  {
    id: "bag-franjas-terracota",
    name: "Bag Franjas Terracota",
    price: 360,
    category: "Bolsas & Sacolas",
    material: "Lã Merino Natural",
    colorTones: ["Terracota"],
    productionMode: "sob-demanda",
    badge: "Em Demanda",
    fiberDescription: "Lã Merino e Franjas Artesanais",
  },
];

export const CATEGORY_COUNTS: Record<ProductCategory, number> = CATEGORIES.reduce(
  (counts, category) => {
    counts[category] = PRODUCTS.filter((product) => product.category === category).length;
    return counts;
  },
  {} as Record<ProductCategory, number>,
);

export const MATERIAL_COUNTS: Record<ProductMaterial, number> = MATERIALS.reduce(
  (counts, material) => {
    counts[material] = PRODUCTS.filter((product) => product.material === material).length;
    return counts;
  },
  {} as Record<ProductMaterial, number>,
);
